// Saga Action
export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
// export const ADD_IMAGES = 'ADD_IMAGES'
export const TRAIN_PRODUCT = 'TRAIN_PRODUCT'
export const GET_ADMIN_PRODUCTS = 'GET_ADMIN_PRODUCTS'
export const GET_ADMIN_PRODUCTS_IMAGES = 'GET_ADMIN_PRODUCTS_IMAGES'
export const GET_ADMIN_PRODUCT_DETAIL = 'GET_ADMIN_PRODUCT_DETAIL'

// Reducer Action
// export const IMAGES_ADDED = 'IMAGES_ADDED'
// export const ADD_IMAGES_ERROR = 'ADD_IMAGES_ERROR'
export const PRODUCT_TRAINED = 'PRODUCT_TRAINED'
export const TRAIN_ERROR = 'TRAIN_ERROR'