// Saga Action
export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const GET_ADMIN_PRODUCTS = 'GET_ADMIN_PRODUCTS'
export const GET_ADMIN_PRODUCTS_IMAGES = 'GET_ADMIN_PRODUCTS_IMAGES'
export const GET_ADMIN_PRODUCT_DETAIL = 'GET_ADMIN_PRODUCT_DETAIL'

// Reducer Action
export const PRODUCT_CREATED = 'PRODUCT_CREATED'
export const CREATE_ERROR = 'CREATE_ERROR'