// Saga Action
export const GET_ADMIN_PRODUCTS = 'GET_ADMIN_PRODUCTS'
export const GET_ADMIN_PRODUCTS_IMAGES = 'GET_ADMIN_PRODUCTS_IMAGES'
export const GET_ADMIN_PRODUCT_DETAIL = 'GET_ADMIN_PRODUCT_DETAIL'